import { Inter, Roboto } from 'next/font/google'
import './globals.css'
import Nav from "./auth/Nav"

const inter = Inter({ subsets: ['latin'] })
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto"
})

// export const metadata: Metadata = {
//   title: 'Create Next App',
//   description: 'Generated by create next app',
// }

export default function RootLayout({children}) {
  return (
    <html lang="en">
      <body className={`mx-4 md:mx-24 xl:mx-96 ${roboto.variable} bg-gray-200`}>
        <Nav />
        {children}
      </body>
    </html>
  )
}
